//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDB
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Password { get; set; }
        public bool isEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
        public string UserName { get; set; }
        public string MiddleName { get; set; }
        public string ResetPasswordCode { get; set; }
    }
}
